name: Label and Create Branch for New Issues

on:
  issues:
    types: [opened, unlabeled]

jobs:
  label-and-create-branch:
    if: startsWith(github.event.issue.title, 'testing')
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: write
      pull-requests: write
      discussions: write
    steps:

      - name: Debug File System
        run: |
          pwd  # Print current working directory
          ls -R  # List all files and directories recursively
          echo "Files in .github/workflows directory:"
          ls -l .github/workflows  # List files in .github/workflows directory
          echo "Contents of conditions.json:"
          cat .github/workflows/conditions.json  # Print contents of conditions.json

      - name: Read conditions from JSON
        id: read-conditions
        run: |
          CONDITIONS=$(cat .github/workflows/conditions.json)
          echo "We made it here"
          echo "::set-output name=CONDITIONS::$CONDITIONS"
          
      - name: Print check
        run: echo "There is an issue containing the word testing"
        
      - name: Add label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: test
        
      - name: Set Branch Name
        id: set-branch-name
        run: |
          # Extract issue title and replace spaces with hyphens
          ISSUE_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-')
          
          echo "Issue title: $ISSUE_TITLE"
          
          # Concatenate issue number and transformed title to form branch name
          BRANCH_NAME="${ISSUE_NUMBER}-${ISSUE_TITLE}"
          echo "full branch name: $BRANCH_NAME"
          
          echo "::set-output name=BRANCH_FULL_NAME::$BRANCH_NAME"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create Branch 
        id: create-branch
        run: |
          echo "We will create a branch with this name: $BRANCH_NAME"
          gh issue develop $ISSUE_NUMBER -b dev -n $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ steps.set-branch-name.outputs.BRANCH_FULL_NAME }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
