name: Label and Create Branch for New Issues

on:
  issues:
    types: [opened, unlabeled]

jobs:
  label-and-create-branch:
    if: startsWith(github.event.issue.title, 'testing')
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: write
      pull-requests: write
      discussions: write
    steps:
      - name: Print check
        run: echo "There is an issue containing the word testing"
        
      - name: Add label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: test
        
      - name: Set Branch Name
        id: set-branch-name
        run: |
          # Extract issue title and replace spaces with hyphens
          ISSUE_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-')
          
          echo "Issue title: $ISSUE_TITLE"
          
          # Concatenate issue number and transformed title to form branch name
          BRANCH_NAME="${ISSUE_NUMBER}-${ISSUE_TITLE}"
          echo "full branch name: $BRANCH_NAME"
          
          echo "::set-output name=BRANCH_FULL_NAME::$BRANCH_NAME"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Branch 
        id: create-branch
        run: |
          echo "We will create a branch with this name: $BRANCH_NAME"
          git checkout main
          git pull
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "::set-output name=BRANCH_FULL_NAME::$BRANCH_NAME"
          echo "::set-output name=BRANCH_SHA::$(git rev-parse HEAD)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ steps.set-branch-name.outputs.BRANCH_FULL_NAME }}
      
      - name: Create Pull Request
        run: gh pr create --title "$BRANCH_NAME" --body "test" --head "$BRANCH_NAME" --base "main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create-branch.outputs.BRANCH_FULL_NAME }}
          BRANCH_SHA: ${{ steps.create-branch.outputs.BRANCH_SHA }}

