name: Label and Create Branch for New Issues

on:
  issues:
    types: [opened, unlabeled]

jobs:
  label-and-create-branch:
    if: startsWith(github.event.issue.title, 'testing')
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: write
      pull-requests: write
      discussions: write
    steps:
      - name: Print check
        run: echo "There is an issue containing the word testing"
        
      - name: Add label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: test
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set Branch Name
        id: set_branch_name
        run: |
          # Extract issue number
          ISSUE_NUMBER=${{ github.event.issue.number }}
          
          # Extract issue title and replace spaces with hyphens
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | tr ' ' '-')
          
          # Concatenate issue number and transformed title to form branch name
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE}"
          
          echo "::set-output name=branch_name::$BRANCH_NAME"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Create Branch and PR
        id: create_branch_pr
        run: |
          git checkout main
          git pull
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "::set-output name=branch_name::$BRANCH_NAME"
          echo "::set-output name=branch_sha::$(git rev-parse HEAD)"
        env:
          BRANCH_NAME: issue-${{ github.event.issue.number }}
      
      - name: Create Pull Request
        run: gh pr create --title "$BRANCH_NAME" --body "test" --head "${{ steps.create_branch_pr.outputs.branch_name }}" --base "main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

