name: Pull Request on Push to branch
on: 
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    types: [opened]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Create PR
        run: |
          echo "Get the list of PR for that branch that are open"
          gh pr list -H ${{ github.ref_name}} -s "open"
          PR_COUNT=$(gh pr list -H ${{ github.ref_name}} -s "open" | wc -l)
          echo $PR_COUNT
          echo "Checking  if there are any PR already"
          if [[ $PR_COUNT -gt 0 ]]; then
            echo "Indeed there is at least one PR for this branch"
          else
            echo "There is no PR for this branch so we create one"
              gh pr create -B $BASE_BRANCH -H $BRANCH_TO_MERGE --title "$PR_TITLE" --body "$PR_BODY"
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_TITLE: "Autocreated PR: ${{ github.ref_name}}"
            PR_BODY: "Created by Github action"
            BASE_BRANCH: "dev"
            BRANCH_TO_MERGE: ${{ github.ref}}

      - name: Get linked issue number to PR
        id: get_issue_number
        run: |
          ISSUE_NUMBER=$(jq --raw-output .issue.url <<< "$(curl -s -H "Authorization: token $GITHUB_TOKEN" ${{ github.event.pull_request.issue_url }})")
          echo "::set-output name=issue_number::$ISSUE_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Copy labels from linked issues
        if: ${{ steps.get_issue_number.outputs.issue_number }}
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.get_issue_number.outputs.issue_number }}


        
            
      
