name: Pull Request on Push to branch
on: 
  push:
    branches-ignore:
      - main
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Create PR
        run: gh pr create -B $BASE_BRANCH -H $BRANCH_TO_MERGE --title "tevd" --body "heiueh"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_TITLE: "Autocreated PR"
            PR_BODY: "Created by Github action"
            BASE_BRANCH: "dev"
            BRANCH_TO_MERGE: ${{ github.ref}}
            
      
