name: Label and Create Branch for New Issues

on:
  issues:
    types: [opened, unlabeled]

jobs:
  label-and-create-branch:
    if: startsWith(github.event.issue.title, 'testing')
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: write
      pull-requests: write
      discussions: write
    steps:
      - name: Print check
        run: echo "There is an issue containing the word testing"
        
      - name: Add label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: test

      - name: Create Branch and PR
        run: gh pr create --title "$BRANCH_NAME" --body "test" --head "$BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BRANCH_NAME: ${{ github.event.issue.number }}-${{ github.event.issue.title }}
